# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities

import tsync_pb2 as tsync__pb2


class SyncStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Sync = channel.stream_unary(
        '/tsync.Sync/Sync',
        request_serializer=tsync__pb2.Chunk.SerializeToString,
        response_deserializer=tsync__pb2.Response.FromString,
        )


class SyncServicer(object):

  def Sync(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SyncServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Sync': grpc.stream_unary_rpc_method_handler(
          servicer.Sync,
          request_deserializer=tsync__pb2.Chunk.FromString,
          response_serializer=tsync__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'tsync.Sync', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
